#!/bin/bash

set -e

[[ -n "$VERBOSE" ]] && set -x

ROOTFS_URL="http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-minirootfs-3.11.3-x86_64.tar.gz"

# Remove existing layers
rm -rf layers *.tar.gz

#
# Layer 1 setup
#

mkdir -p layers/1
wget "$ROOTFS_URL"
tar -zxf *.tar.gz -C layers/1
rm -rf *.tar.gz
mknod -m 622 layers/1/dev/console c 5 1
mknod -m 666 layers/1/dev/null c 1 3
mknod -m 666 layers/1/dev/zero c 1 5
mknod -m 666 layers/1/dev/ptmx c 5 2
mknod -m 666 layers/1/dev/tty c 5 0
mknod -m 444 layers/1/dev/random c 1 8
mknod -m 444 layers/1/dev/urandom c 1 9
chown -v root:tty layers/1/dev/{console,ptmx,tty}

#
# Layer 2 setup
#

mkdir -p layers/2/etc
echo "nameserver 1.1.1.1" >> layers/2/etc/resolv.conf
LOWER_DIR=layers/1 UPPER_DIR=layers/2 ./runtime-exec /bin/sh -c "apk update && apk add apache2"
echo "ServerName localhost" >> layers/2/etc/apache2/httpd.conf
